^ Welcome to Acmeism

*Acmeism* is the belief that language naturally tends to divide people and ideas, but that technology can overcome this tendency. People who create technology that is not limited to a particular language are known as *Acmeists*.

Most people learn one natural (spoken) language. Most computer programmers learn one programming language. People are natually bound to thinking only in this language. People who invent things, invent them to serve the language that they know. Even when people learn more than one language, they generally do not create things to serve all these languages.

Acmeists believe that their ideas need to be shared across language boundaries. Even though the world is not currently set up to facilitate this, they realize that this does not need to be the case. The more effort people put into sharing their ideas, the easier they will make it to do so.
