^ Acmeist Projects

These are some Acmeist programming projects. They all intend to serve as many programming languages as possible.

* "YAML"<http://yaml.org> - A Serialization Language for all Programming Languages
* "C'Dent"<http://cdent.org> - A Language for Writing Portable Modules
* "TestML"<http://testml.org> - A Language for Writing Portable Unit Tests
* "Stardoc"<http://stardoc.org> - A Framework for Portable Documentation

This is list is currently small. If you have a project to add, please contact us.

