^ Acmeist Projects

These are some Acmeist programming projects. They all intend to serve as many cultures, communities and languages as possible.

* "YAML"<http://yaml.org> - A Serialization Language for many Programming Languages
* "C'Dent"<http://cdent.org> - A Language for Writing Portable Modules
* "TestML"<http://testml.org> - A Language for Writing Portable Unit Tests
* "Pegex"<http://pegex.org> - PEG/Regexp Parser Framework for many Programming Languages
* "Stardoc"<http://stardoc.org> - A Framework for Portable Documentation
* "Wikiwyg"<http://wikiwyg.net> - A Rich-text, Multi-mode editor for all Wikis
* "Jemplate"<http://jemplate.net> - A Programming Template Framework for many Languages
* "JSYnc"<http://jsync.org> - JSON + YAML == Simple Serialization
* "Muldis D"<http://www.muldis.com> - An Object-Relational Language (SQL) for many DBMSs

This is list is currently small. If you have a project to add, please contact us.

